logLevel: info
wsEndpoint: "wss://kusama-rpc.polkadot.io/"
targets:
- alias: validator-000
    validatorAddress: "<validator-000-stash-address>"
- alias: validator-001
  validatorAddress: "<validator-001-stash-address>"
deepCheck:
  enabled: false
claim:
  enabled: false
  batchSize: 4
  gracePeriod:
    enabled: false
    eras: 4
  claimerKeystore:
    filePath: /path/to/validator-000/keystore
    passwordPath: /path/to/validator-000/keystore/password